spring:
  application:
    name: spring-boot-3-jwt-security-6
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: root
    password: P@ss123!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
